// generated by ChatGPT & translated from python version
#include <stdio.h>
#include <stdlib.h>

int main() {
    int m, n;
    scanf("%d %d", &m, &n);

    // 输入数组
    int** inputs = (int**)malloc((m+1) * sizeof(int*));
    for (int i = 0; i <= m; i++) {
        inputs[i] = (int*)malloc((n+1) * sizeof(int));
    }

    // 初始化 inputs 数组
    for (int i = 1; i <= m; i++) {
        for (int j = 1; j <= n; j++) {
            scanf("%d", &inputs[i][j]);
        }
    }

    // 动态规划数组
    int**** dp = (int****)malloc((m+1) * sizeof(int***));
    for (int i = 0; i <= m; i++) {
        dp[i] = (int***)malloc((n+1) * sizeof(int**));
        for (int j = 0; j <= n; j++) {
            dp[i][j] = (int**)malloc((m+1) * sizeof(int*));
            for (int k = 0; k <= m; k++) {
                dp[i][j][k] = (int*)malloc((n+1) * sizeof(int));
            }
        }
    }

    // 初始化 dp 数组为 0
    for (int i = 0; i <= m; i++) {
        for (int j = 0; j <= n; j++) {
            for (int x = 0; x <= m; x++) {
                for (int y = 0; y <= n; y++) {
                    dp[i][j][x][y] = 0;
                }
            }
        }
    }

    // 动态规划填充 dp 数组
    for (int i = 1; i <= m; i++) {
        for (int j = 1; j <= n; j++) {
            for (int x = 1; x <= m; x++) {
                for (int y = 1; y <= n; y++) {
                    if (x == i && y == j) {
                        break;
                    }
                    int max_val = dp[i-1][j][x-1][y];
                    if (dp[i-1][j][x][y-1] > max_val) {
                        max_val = dp[i-1][j][x][y-1];
                    }
                    if (dp[i][j-1][x-1][y] > max_val) {
                        max_val = dp[i][j-1][x-1][y];
                    }
                    if (dp[i][j-1][x][y-1] > max_val) {
                        max_val = dp[i][j-1][x][y-1];
                    }
                    dp[i][j][x][y] = max_val + inputs[i][j] + inputs[x][y];
                }
            }
        }
    }

    // 输出结果
    printf("%d\n", dp[m-1][n][m][n-1]);

    // 释放内存
    for (int i = 0; i <= m; i++) {
        for (int j = 0; j <= n; j++) {
            for (int x = 0; x <= m; x++) {
                free(dp[i][j][x]);
            }
            free(dp[i][j]);
        }
        free(dp[i]);
    }
    free(dp);

    for (int i = 0; i <= m; i++) {
        free(inputs[i]);
    }
    free(inputs);

    return 0;
}
